---
title: "ISLR Linear Regression"
output: html_notebook
---

```{r setup, echo=FALSE}

library(ISLR)
library(tidyverse)
library(ggplot2)

# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

```

```{r advertising_data, echo=FALSE}
advertising = read_csv("Data/advertising.csv")
```

Podemos observar uma relação linear entre anúncios na TV e anúncios no rádio e as vendas.  Em relação a anúncios em jornal, a relação linear parece ser bem mais fraca.
```{r simple_lm, echo=FALSE}
tv_lm_fit = lm(Sales ~ TV, data = advertising)
radio_lm_fit = lm(Sales ~ Radio, data = advertising)
newspaper_lm_fit = lm(Sales ~ Newspaper, data = advertising)

tv = advertising %>% ggplot(aes(x = TV, y = Sales)) + geom_point() +
  geom_abline(intercept = tv_lm_fit$coefficients[[1]],
              slope = tv_lm_fit$coefficients[[2]], color = "red")


radio = advertising %>% ggplot(aes(x = Radio, y = Sales)) + geom_point() +
  geom_abline(intercept = radio_lm_fit$coefficients[[1]],
              slope = radio_lm_fit$coefficients[[2]], color = "red")

newspaper = advertising %>% ggplot(aes(Newspaper, Sales)) + geom_point() +
  geom_abline(intercept = newspaper_lm_fit$coefficients[[1]],
              slope = newspaper_lm_fit$coefficients[[2]], color = "red")

multiplot(tv, radio, newspaper, cols=2)
```
```{r}
tv_sum = summary(tv_lm_fit)
tv_sum$coefficients
```
```{r}
radio_sum = summary(radio_lm_fit)
radio_sum$coefficients
```

```{r}
newspaper_sum = summary(newspaper_lm_fit)
newspaper_sum$coefficients
```

